# Generated by Django 5.2.8 on 2025-12-28 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("communications", "0001_initial"),
        ("missions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="messagegroup",
            name="mission",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_group",
                to="missions.mission",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communications.messagegroup",
            ),
        ),
        migrations.AddField(
            model_name="groupmember",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_members",
                to="communications.messagegroup",
            ),
        ),
        migrations.AddField(
            model_name="messagereadreceipt",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="read_receipts",
                to="communications.message",
            ),
        ),
        migrations.AddField(
            model_name="messagereadreceipt",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_read_receipts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="messagegroup",
            index=models.Index(
                fields=["mission", "status"], name="message_gro_mission_40d39c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["group", "created_at"], name="messages_group_i_029d41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="messages_sender__bf8b1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["group", "role"], name="group_membe_group_i_319a8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(fields=["user"], name="group_membe_user_id_88c209_idx"),
        ),
        migrations.AddConstraint(
            model_name="groupmember",
            constraint=models.UniqueConstraint(
                fields=("group", "user"), name="unique_group_member"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadreceipt",
            index=models.Index(
                fields=["message", "read_at"], name="message_rea_message_3e8d62_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereadreceipt",
            constraint=models.UniqueConstraint(
                fields=("message", "user"), name="unique_message_read"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_a4dd5c_idx"
            ),
        ),
    ]
