# Generated by Django 5.2.8 on 2025-12-28 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("missions", "0001_initial"),
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="sdg",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="missions",
                to="skills.sustainabledevelopmentgoal",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="mission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="missions.mission",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="volunteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to="accounts.volunteerprofile",
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["status", "start_date"], name="missions_status_c292c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["organization", "status"], name="missions_organiz_25f9c1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="mission",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="end_date_after_start_date",
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["status", "applied_at"], name="participati_status_2b9fa1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["volunteer", "status"], name="participati_volunte_a680e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["volunteer_rating"], name="participati_volunte_587010_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="participation",
            index=models.Index(
                fields=["organization_rating"], name="participati_organiz_d1f106_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("mission", "volunteer"), name="unique_mission_volunteer"
            ),
        ),
    ]
