# Generated by Django 5.2.8 on 2025-12-28 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("missions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SustainableDevelopmentGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.PositiveIntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("icon_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "db_table": "sustainable_development_goals",
                "ordering": ["number"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Skill categories",
                "db_table": "skill_categories",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "verification_requirement",
                    models.CharField(
                        choices=[
                            ("none", "No Verification Required"),
                            ("document", "Document Verification"),
                            ("test", "Skill Test Required"),
                            ("endorsement", "Peer Endorsement Required"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="skills",
                        to="skills.skillcategory",
                    ),
                ),
            ],
            options={
                "db_table": "skills",
            },
        ),
        migrations.CreateModel(
            name="MissionSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requirement_level",
                    models.CharField(
                        choices=[
                            ("nice_to_have", "Nice to Have"),
                            ("preferred", "Preferred"),
                            ("required", "Required"),
                            ("critical", "Critical"),
                        ],
                        default="preferred",
                        max_length=20,
                    ),
                ),
                ("is_verification_required", models.BooleanField(default=False)),
                (
                    "min_proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_skills",
                        to="missions.mission",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_skills",
                        to="skills.skill",
                    ),
                ),
            ],
            options={
                "db_table": "mission_skills",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mission", "skill"), name="unique_mission_skill"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VolunteerSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Verification"),
                            ("verified", "Verified"),
                            ("rejected", "Verification Rejected"),
                            ("not_required", "Verification Not Required"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verification_date", models.DateTimeField(blank=True, null=True)),
                ("verification_notes", models.TextField(blank=True, null=True)),
                (
                    "supporting_document",
                    models.FileField(
                        blank=True, null=True, upload_to="skill_verifications/"
                    ),
                ),
                ("supporting_url", models.URLField(blank=True, null=True)),
                ("last_used_date", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_skills",
                        to="skills.skill",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_skills",
                        to="accounts.volunteerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_skills",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "skill"), name="unique_volunteer_skill"
                    )
                ],
            },
        ),
    ]
