# Generated by Django 5.2.8 on 2025-12-29 17:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerskill",
            name="verification_documents",
            field=models.FileField(
                blank=True, null=True, upload_to="skill_verification_docs/"
            ),
        ),
        migrations.AddField(
            model_name="volunteerskill",
            name="verification_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="volunteerskill",
            name="verification_request_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="volunteerskill",
            name="verification_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="VerificationRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "request_documents",
                    models.FileField(
                        blank=True, null=True, upload_to="verification_requests/"
                    ),
                ),
                ("request_links", models.JSONField(blank=True, default=list)),
                ("request_notes", models.TextField(blank=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_more_info", "Needs More Information"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "volunteer_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_requests",
                        to="skills.volunteerskill",
                    ),
                ),
            ],
            options={
                "db_table": "verification_requests",
                "ordering": ["-request_date"],
            },
        ),
    ]
